Better ipfs
Shyft-to/shyft-solana-api pull request #13
Opened 2022-07-11 16:07 UTC by codinpsycho

Better reads, index all NFTs from a wallet and using nftstorage.link on create
Other null checks and improvements

2022-07-11 16:26 UTC, vgvishesh requested changes

2022-07-11 16:26 UTC, vgvishesh commented on src/modules/db/remote-data-fetcher/data-fetcher.service.ts
> +      console.log('error occurred for', uri);
We should throw exception here, and how to handle it or not should be decided by the caller function.

2022-07-11 16:26 UTC, vgvishesh commented on src/modules/nft/components/create-nft/dto/create-nft.dto.ts
> +    type: String,
This is not a string, it is a json array.

2022-07-11 16:26 UTC, vgvishesh commented on src/modules/nft/components/read-nft/read-nft.service.ts
>        //Right now its being fetched from chain only
Remove this comment.

2022-07-11 16:34 UTC, codinpsycho commented on src/modules/nft/components/create-nft/dto/create-nft.dto.ts
> +    type: String,
Remember Abhirup had to stringify it.

2022-07-12 05:31 UTC, vgvishesh approved these changes

2022-07-12 05:32 UTC, merged